kind: pipeline
name: default

steps:
  # - name: install
  #   image: composer
  #   commands:
  #   - composer install
  - name: scp files
    image: appleboy/drone-scp
    settings:
      host: 
        from_secret: home_host
      username: 
        from_secret: home_user
      key: 
        from_secret: home_key
      port: 22
      target: /home/deploy/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      source: ./
